# Generated by Django 5.0.6 on 2024-06-08 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='image',
        ),
    ]
