# Generated by Django 5.0.6 on 2024-06-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_taskitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
